In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
df=pd.read_csv("adagency.csv")

In [3]:
df.head()

,Print Media Expenses,Social Media Expenses,Outdoor Ad Expenses,City,Profit
0,165349.20,136897.80,471784.10,Mumbai,192261.83
1,162597.70,151377.59,443898.53,Chandigarh,191792.06
2,153441.51,101145.55,407934.54,Delhi,191050.39
3,144372.41,118671.85,383199.62,Mumbai,182901.99
4,142107.34,91391.77,366168.42,Delhi,166187.94

In [4]:
x=df.iloc[:,:4]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Print Media Expenses   50 non-null     float64
 1   Social Media Expenses  50 non-null     float64
 2   Outdoor Ad Expenses    50 non-null     float64
 3   City                   50 non-null     object
 4   Profit                 50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [6]:
from sklearn.compose import ColumnTransformer

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
ct = ColumnTransformer(
    transformers=[("encoder", OneHotEncoder(), [3])], 
    remainder="passthrough",
    sparse_threshold=0  # Forces dense output
)
x = ct.fit_transform(x)

In [11]:
x=pd.DataFrame(x)

In [13]:
x

      0    1    2          3          4          5
0   0.0  0.0  1.0  165349.20  136897.80  471784.10
1   1.0  0.0  0.0  162597.70  151377.59  443898.53
2   0.0  1.0  0.0  153441.51  101145.55  407934.54
3   0.0  0.0  1.0  144372.41  118671.85  383199.62
4   0.0  1.0  0.0  142107.34   91391.77  366168.42
5   0.0  0.0  1.0  131876.90   99814.71  362861.36
6   1.0  0.0  0.0  134615.46  147198.87  127716.82
7   0.0  1.0  0.0  130298.13  145530.06  323876.68
8   0.0  0.0  1.0  120542.52  148718.95  311613.29
9   1.0  0.0  0.0  123334.88  108679.17  304981.62
10  0.0  1.0  0.0  101913.08  110594.11  229160.95
11  1.0  0.0  0.0  100671.96   91790.61  249744.55
12  0.0  1.0  0.0   93863.75  127320.38  249839.44
13  1.0  0.0  0.0   91992.39  135495.07  252664.93
14  0.0  1.0  0.0  119943.24  156547.42  256512.92
15  0.0  0.0  1.0  114523.61  122616.84  261776.23
16  1.0  0.0  0.0   78013.11  121597.55  264346.06
17  0.0  0.0  1.0   94657.16  145077.58  282574.31
18  0.0  1.0  0.0   91749.16  114175.79  294919.57
19  0.0  0.0  1.0   86419.70  153514.11       0.00
20  1.0  0.0  0.0   76253.86  113867.30  298664.47
21  0.0  0.0  1.0   78389.47  153773.43  299737.29
22  0.0  1.0  0.0   73994.56  122782.75  303319.26
23  0.0  1.0  0.0   67532.53  105751.03  304768.73
24  0.0  0.0  1.0   77044.01   99281.34  140574.81
25  1.0  0.0  0.0   64664.71  139553.16  137962.62
26  0.0  1.0  0.0   75328.87  144135.98  134050.07
27  0.0  0.0  1.0   72107.60  127864.55  353183.81
28  0.0  1.0  0.0   66051.52  182645.56  118148.20
29  0.0  0.0  1.0   65605.48  153032.06  107138.38
30  0.0  1.0  0.0   61994.48  115641.28   91131.24
31  0.0  0.0  1.0   61136.38  152701.92   88218.23
32  1.0  0.0  0.0   63408.86  129219.61   46085.25
33  0.0  1.0  0.0   55493.95  103057.49  214634.81
34  1.0  0.0  0.0   46426.07  157693.92  210797.67
35  0.0  0.0  1.0   46014.02   85047.44  205517.64
36  0.0  1.0  0.0   28663.76  127056.21  201126.82
37  1.0  0.0  0.0   44069.95   51283.14  197029.42
38  0.0  0.0  1.0   20229.59   65947.93  185265.10
39  1.0  0.0  0.0   38558.51   82982.09  174999.30
40  1.0  0.0  0.0   28754.33  118546.05  172795.67
41  0.0  1.0  0.0   27892.92   84710.77  164470.71
42  1.0  0.0  0.0   23640.93   96189.63  148001.11
43  0.0  0.0  1.0   15505.73  127382.30   35534.17
44  1.0  0.0  0.0   22177.74  154806.14   28334.72
45  0.0  0.0  1.0    1000.23  124153.04    1903.93
46  0.0  1.0  0.0    1315.46  115816.21  297114.46
47  1.0  0.0  0.0       0.00  135426.92       0.00
48  0.0  0.0  1.0     542.05   51743.15       0.00
49  1.0  0.0  0.0       0.00  116983.80   45173.06

In [15]:
x=x.drop(columns=0)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
y=df["Profit"]

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [24]:
x_train.shape

(40, 5)

In [25]:
y_train.shape

(40,)

In [27]:
x_test.shape

(10, 5)

In [28]:
y_test.shape

(10,)

In [29]:
model=LinearRegression()

In [30]:
model.fit(x_train,y_train)

LinearRegression()

In [31]:
y_predict=model.predict(x_test)

In [32]:
from sklearn import metrics

In [33]:
metrics.mean_absolute_error(y_test,y_predict)

7514.293659641064

In [34]:
metrics.mean_squared_error(y_test,y_predict)

83502864.03256819

In [36]:
np.sqrt(metrics.mean_squared_error(y_test,y_predict))

np.float64(9137.990152794442)

In [39]:
# adjusted R value calculation
from sklearn.metrics import r2_score

from sklearn.metrics import r2_score

# Assuming y_test, y_predict, and X_test are defined
R = r2_score(y_test, y_predict) 
n = len(y_test)
p = x_test.shape[1] # p is the number of predictors (columns)
adj_r = 1 - (1 - R) * (n - 1) / (n - p - 1)

In [40]:
print(adj_r)

0.8530904064885618